<%@ page language="java" %>
<%@ page import="
	com.epoch.chem.MolString,
	com.epoch.qBank.Question,
	com.epoch.utils.Utils"
%>
<%
	final String pathToRoot = "../";
	final String substrate = 
			"<?xml version=\"1.0\" encoding=\"MacRoman\"?>"
			+ "<cml version=\"ChemAxon file format v6.0, generated by v6.0.3\">"
			+ "<MDocument>"
			+ "<MChemicalStruct>"
			+ "<molecule molID=\"m1\">"
			+ "<atomArray atomID=\"a1 a2 a3 a4 a5\" elementType=\"C C C C O\" "
				+ "x2=\"-5.994999885559082 -4.661320763731046 -3.327641641903011 -1.9939625200749758 -0.66028339824694\" "
				+ "y2=\"3.134999990463257 3.904999990463257 3.134999990463257 3.904999990463257 3.134999990463257\"/>"
			+ "<bondArray>"
			+ "<bond atomRefs2=\"a1 a2\" order=\"1\"/>"
			+ "<bond atomRefs2=\"a2 a3\" order=\"1\"/>"
			+ "<bond atomRefs2=\"a3 a4\" order=\"1\"/>"
			+ "<bond atomRefs2=\"a4 a5\" order=\"1\"/>"
			+ "</bondArray>"
			+ "</molecule>"
			+ "</MChemicalStruct>"
			+ "</MDocument>"
			+ "</cml>";
%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<head>
<title> Test of Context Menu for SVG Images </title>
<link rel="stylesheet" href="../includes/epoch.css" type="text/css"/>
<style type="text/css">
	.cmenu {margin: 0; padding: 0.3em; list-style-type: none; background-color: white;}
	.cmenu li:hover {}
	.cmenu hr {border: 0; border-bottom: 1px solid grey; margin: 3px 0px 3px 0px; width: 10em;}
	.cmenu a {border: 0 !important;}
	.cmenu a:hover {text-decoration: underline !important;}
	.cmenu .topSep {font-size: 90%; border-top: 1px solid gray; margin-top: 0.3em; padding-top: 0.3em;}
</style>

<script src="<%= pathToRoot %>js/jslib.js" type="text/javascript"></script>
<script type="text/javascript">

	// <!-- >
	var _replaceContext = false; // replace the system context menu?
	var _mouseOverContext = false; // is the mouse over the context menu?
	var _noContext = false; // disable the context menu?
	var _divContext; // makes my life easier

	function InitContext() {
		_divContext = $('divContext');
		_divContext.onmouseover = function() { _mouseOverContext = true; };
		_divContext.onmouseout = function() { _mouseOverContext = false; };

		$('aDisable').onclick = DisableContext;
		$('aEnable').onclick = EnableContext;

		document.body.onmousedown = ContextMouseDown;
		document.body.oncontextmenu = ContextShow;
	} // InitContext()

	// call from the onMouseDown event, passing the event if standards compliant
	function ContextMouseDown(event) {
		if (_noContext || _mouseOverContext) return;

		// IE is evil and doesn't pass the event object
		if (!event) event = window.event;

		// we assume we have a standards compliant browser, but check if we have IE
		var target = event.target ? event.target : event.srcElement;

		// only show the context menu if the right mouse button is pressed
		//   and a hyperlink has been clicked (the code can be made more selective)
		if (event.button === 2 && target.tagName.toLowerCase() === 'svg') _replaceContext = true;
		else if (!_mouseOverContext) _divContext.style.display = 'none';
	} // ContextMouseDown()

	function CloseContext() {
		_mouseOverContext = false;
		_divContext.style.display = 'none';
	} // CloseContext()

	// call from the onContextMenu event, passing the event
	// if this function returns false, the browser's context menu will not show up
	function ContextShow(event) {
		if (_noContext || _mouseOverContext) return;

		// IE is evil and doesn't pass the event object
		if (!event) event = window.event;

		// we assume we have a standards compliant browser, but check if we have IE
		var target = event.target ? event.target : event.srcElement;

		if (_replaceContext) {
			$('aSource').href = 'javascript:window.prompt(\'Press Cmd+C, then enter\', \'<%= Utils.toValidJS(substrate) %>\');';

			// document.body.scrollTop does not work in IE
			var scrollTop = document.body.scrollTop ? document.body.scrollTop 
					: document.documentElement.scrollTop;
			var scrollLeft = document.body.scrollLeft ? document.body.scrollLeft 
					: document.documentElement.scrollLeft;

			// hide the menu first to avoid an "up-then-over" visual effect
			_divContext.style.display = 'none';
			_divContext.style.left = event.clientX + scrollLeft + 'px';
			_divContext.style.top = event.clientY + scrollTop + 'px';
			_divContext.style.display = 'block';

			_replaceContext = false;

			return false;
		} // if (_replaceContext)
	} // ContextShow()

	function DisableContext() {
		_noContext = true;
		CloseContext();
		// $('aEnable').style.display = '';
		return false;
	} // DisableContext()

	function EnableContext() {
		_noContext = false;
		_mouseOverContext = false; // this gets left enabled when "disable menus" is chosen
		// $('aEnable').style.display = 'none';
		return false;
	} // EnableContext()

	// comes from prototype.js; this is simply easier on the eyes and fingers
	function $(id) {
		return document.getElementById(id);
	} // $()
	//-->

</script>
</head>

<body style="overflow:auto;" onload="InitContext();">

<br/>

<!-- self submit form -->
<input type="hidden" name="substrate" value=""/>
<p class="boldtext big" style="text-align:center;">
Test of Context Menu for SVG Images
</p>
<p>
<table style="width:500px; margin-left:auto; margin-right:auto;">
<tr><td class="regtext">
Right-click on the structure and copy its MRV.
</td></tr>
</table>
<br/>

<table style="width:500px; margin-left:auto; margin-right:auto;">
<tr>
<td style="text-align:center; width:100%;" id="imgCell">
	<a id="aEnable" style=""><%= MolString.getImage(pathToRoot, substrate) %></a>
</td>
</tr>
</table>

<br/>
<br/>

<table style="width:500px; margin-left:auto; margin-right:auto;">
<tr>
<td align="left" class="regtext" >
<a href="welcome.html">Back</a> to public ACE pages.
</td>
</tr>
</table>

<div id="divContext" style="border:1px solid blue; display:none; position:absolute;">
<ul class="cmenu">
<li><a id="aSource" href="#">Copy source</a></li>
<li><a id="aDisable" href="#">Disable this menu</a></li>
</ul>
</div>


</body>
</html>
