package com.epoch.responses;

/** A stored response to a question. Used in the feedback improver (View
 * Responses).
*/
public class StoredResponse /* implements Comparable<Object> */ {

	/** Correct or incorrect response. */
	public int type;
		/** Value for type.  */
		public static final int CORRECT = 1;
		/** Value for type.  */
		public static final int WRONG = 2; 
	
	/** Feedback generated by this response. */
	public String feedback;
	/** Major ID of evaluator satisfied by this response. */
	public int matchingEvaluatorMajorId;
	/** Minor ID of evaluator satisfied by this response. */
	public int matchingEvaluatorMinorId; // apparently unread

	/** Number of times this response was given. */
	public int numEntries;
	/** Whether this response satisfied an evaluator. */
	public boolean feedbackExists;
	/** String representation of this response. */
	public String response;

	/* Determines whether this response was given more frequently than another.
	 * @param	otherObj	another response
	 * @return	1 if this response was less frequent than the other, 0 if
	 * equally frequent, -1 otherwise 
	public int compareTo(Object otherObj) {
		final StoredResponse other = (StoredResponse) otherObj;
		// knowingly reversed the conventions so that Array.sort()
		// will return in descending order
		return (this.numEntries < other.numEntries ? 1
				: this.numEntries > other.numEntries ? -1
				: 0);
	} // compareTo(Object)
	 */

} // StoredResponse

