<?xml version="1.0" encoding="UTF-8"?>
<%@ page language="java" %>
<%@ page import="
	chemaxon.formats.MolImporter,
	chemaxon.sss.SearchConstants,
	chemaxon.sss.search.MolSearch,
	chemaxon.sss.search.MolSearchOptions,
	chemaxon.struc.Molecule,
	chemaxon.struc.StereoConstants,
	com.epoch.utils.Utils "
%>
<%
		int[] isomorphism = new int[0];
		String targetMolStr = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" + 
				"<cml xmlns=\"http://www.chemaxon.com\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.chemaxon.com/marvin/help/formats/schema/mrvSchema_14_7_7.xsd\" version=\"ChemAxon file format v14.7.7, generated by v14.7.7.0\">\n" + 
				"<MDocument>\n" + 
				"  <MChemicalStruct>\n" + 
				"    <molecule title=\"propranolol\" molID=\"m1\">\n" + 
				"      <atomArray atomID=\"a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16 a17 a18 a19 a20 a21 a22 a23 a24 a25 a26 a27 a28 a29 a30 a31 a32 a33 a34 a35 a36 a37 a38 a39 a40 a41 a42 a43 a44 a45 a46 a47 a48 a49 a50 a51 a52 a53 a54 a55 a56 a57 a58 a59 a60 a61 a62 a63 a64 a65 a66 a67 a68 a69 a70 a71 a72 a73 a74 a75 a76 a77 a78 a79 a80 a81 a82 a83 a84 a85 a86 a87 a88 a89 a90 a91 a92 a93 a94 a95 a96 a97 a98 a99 a100 a101 a102 a103 a104\" elementType=\"C C C N C C O C O C C C C C C C C C C C N C C C C C O C C C C C C C C N C C C C F C C C C O N C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C\" mrvMap=\"0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\" mrvPseudo=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H\" x2=\"-9.762216616058154 -8.42853749423012 -8.42853749423012 -7.094858372402084 -5.761179250574048 -4.427500128746012 -4.427500128746013 -3.0938210069179775 -1.7601418850899422 -0.426462763261906 0.9072163585661324 0.9072163585661359 2.2408954803941734 3.5745746022222065 3.574574602222203 2.240895480394167 2.240895480394167 0.9072163585661315 -0.42646276326190424 6.423814821383884 7.757493943211919 7.757493943211919 9.091173065039953 10.42485218686799 11.758531308696025 13.092210430524062 14.556837465618596 14.5568374656186 13.092210430524062 12.465836000187327 10.934272281320185 10.029082992789778 10.655457423126514 12.187021141993654 10.30789785098345 9.681523420646716 13.718584860860794 12.813395572330382 13.439770002667114 14.971333721534254 15.597708151870986 15.876523010064666 15.250148579727934 22.01104321354868 22.011043213548685 20.67736409172065 23.344722335376723 23.344722335376723 24.67840145720476 24.67840145720476 23.344722335376726 22.01104321354869 22.011043213548685 -8.992216616058153 -11.09589573788619 -10.532216616058156 -9.762216616058156 -9.96853749423012 -8.42853749423012 -6.88853749423012 -7.094858372402083 -6.028597444181122 -5.038193043883776 -5.761179250574048 -3.093821006917978 -3.81680721360825 -2.3708348002277053 -0.4264627632618976 2.2408954803941783 4.908253724050244 4.908253724050237 3.574574602222202 0.9072163585661313 -1.7601418850899393 6.591192777208151 4.909822833960908 5.341113947667791 6.034636750130866 7.122692503123944 9.212614511295852 7.98193044129613 9.621532751747 9.277337054815748 11.729189544066035 10.856183356603882 12.73925478490872 16.18067999089782 15.132417599369044 13.1194293446961 8.615292084458975 9.287930764090728 11.959026245253312 13.191355748216324 17.431984964524645 16.85212102403771 23.55104321354868 22.011043213548678 20.471043213548683 24.678401457204757 26.012080579032794 26.012080579032798 23.34472233537673 20.677364091720655 20.677364091720648\" y2=\"-7.3150002479553375 -8.085000247955337 -9.625000247955338 -7.315000247955337 -8.085000247955337 -7.3150002479553375 -5.7750002479553375 -8.085000247955337 -7.3150002479553375 -8.085000247955339 -7.315000247955336 -5.775000247955332 -5.005000247955335 -5.775000247955338 -7.315000247955339 -8.085000247955337 -9.625000247955338 -10.395000247955338 -9.625000247955338 -5.704446576798793 -6.474446576798792 -8.014446576798791 -5.704446576798791 -6.474446576798791 -5.70444657679879 -6.47444657679879 -6.95033274813621 -8.49033274813621 -8.96621891947363 -10.373078924243238 -10.534052757675422 -9.288166586338 -7.881306581568396 -7.720332748136209 -11.940912762445025 -13.347772767214629 -5.067586572029184 -3.8217004006917623 -2.414840395922157 -2.2538665624899705 -0.8470065577203654 -3.49975273382739 -4.906612738596995 -4.042499923706055 -5.582499923706056 -6.352499923706057 -6.352499923706054 -7.892499923706054 -8.662499923706054 -10.202499923706053 -10.972499923706055 -10.202499923706057 -8.662499923706058 -5.981321126127302 -6.545000247955337 -8.648679369783373 -8.855000247955337 -9.625000247955338 -11.165000247955337 -9.625000247955338 -5.775000247955337 -9.601604187594138 -9.444739540958084 -6.545000247955338 -5.005000247955337 -9.444739540958084 -9.444739540958086 -5.005000247955328 -3.4650002479553352 -5.005000247955342 -8.085000247955342 -10.39500024795534 -11.935000247955337 -10.39500024795534 -4.108574400230963 -5.010625302352678 -6.931083990023432 -8.039088714332445 -9.739248493610559 -8.880505873369515 -4.190818612497336 -4.251699239625948 -7.759273713655997 -6.947013230299381 -4.249229590723032 -4.7725840250172675 -8.834210913269178 -10.030830692548786 -11.85665208084675 -10.455952654956848 -6.737473134964555 -2.303905922623264 -0.7641422862356555 -3.0519648574111886 -5.318969130976138 -4.0424999237060515 -2.502499923706055 -4.042499923706059 -5.5824999237060515 -7.892499923706054 -10.972499923706053 -12.512499923706056 -10.97249992370606 -7.89249992370606\"/>\n" + 
				"      <bondArray>\n" + 
				"        <bond id=\"b1\" atomRefs2=\"a1 a2\" order=\"1\"/>\n" + 
				"        <bond id=\"b2\" atomRefs2=\"a2 a3\" order=\"1\"/>\n" + 
				"        <bond id=\"b3\" atomRefs2=\"a2 a4\" order=\"1\"/>\n" + 
				"        <bond id=\"b4\" atomRefs2=\"a4 a5\" order=\"1\"/>\n" + 
				"        <bond id=\"b5\" atomRefs2=\"a5 a6\" order=\"1\"/>\n" + 
				"        <bond id=\"b6\" atomRefs2=\"a6 a7\" order=\"1\"/>\n" + 
				"        <bond id=\"b7\" atomRefs2=\"a6 a8\" order=\"1\"/>\n" + 
				"        <bond id=\"b8\" atomRefs2=\"a8 a9\" order=\"1\"/>\n" + 
				"        <bond id=\"b9\" atomRefs2=\"a9 a10\" order=\"1\"/>\n" + 
				"        <bond id=\"b10\" atomRefs2=\"a10 a11\" order=\"A\"/>\n" + 
				"        <bond id=\"b11\" atomRefs2=\"a11 a12\" order=\"A\"/>\n" + 
				"        <bond id=\"b12\" atomRefs2=\"a12 a13\" order=\"A\"/>\n" + 
				"        <bond id=\"b13\" atomRefs2=\"a13 a14\" order=\"A\"/>\n" + 
				"        <bond id=\"b14\" atomRefs2=\"a14 a15\" order=\"A\"/>\n" + 
				"        <bond id=\"b15\" atomRefs2=\"a15 a16\" order=\"A\"/>\n" + 
				"        <bond id=\"b16\" atomRefs2=\"a11 a16\" order=\"A\"/>\n" + 
				"        <bond id=\"b17\" atomRefs2=\"a16 a17\" order=\"A\"/>\n" + 
				"        <bond id=\"b18\" atomRefs2=\"a17 a18\" order=\"A\"/>\n" + 
				"        <bond id=\"b19\" atomRefs2=\"a18 a19\" order=\"A\"/>\n" + 
				"        <bond id=\"b20\" atomRefs2=\"a10 a19\" order=\"A\"/>\n" + 
				"        <bond id=\"b21\" atomRefs2=\"a20 a21\" order=\"1\"/>\n" + 
				"        <bond id=\"b22\" atomRefs2=\"a21 a22\" order=\"1\"/>\n" + 
				"        <bond id=\"b23\" atomRefs2=\"a21 a23\" order=\"1\"/>\n" + 
				"        <bond id=\"b24\" atomRefs2=\"a23 a24\" order=\"1\"/>\n" + 
				"        <bond id=\"b25\" atomRefs2=\"a24 a25\" order=\"1\"/>\n" + 
				"        <bond id=\"b26\" atomRefs2=\"a25 a26\" order=\"1\"/>\n" + 
				"        <bond id=\"b27\" atomRefs2=\"a26 a27\" order=\"1\"/>\n" + 
				"        <bond id=\"b28\" atomRefs2=\"a27 a28\" order=\"1\"/>\n" + 
				"        <bond id=\"b29\" atomRefs2=\"a28 a29\" order=\"1\"/>\n" + 
				"        <bond id=\"b30\" atomRefs2=\"a29 a30\" order=\"A\"/>\n" + 
				"        <bond id=\"b31\" atomRefs2=\"a30 a31\" order=\"A\"/>\n" + 
				"        <bond id=\"b32\" atomRefs2=\"a31 a32\" order=\"A\"/>\n" + 
				"        <bond id=\"b33\" atomRefs2=\"a32 a33\" order=\"A\"/>\n" + 
				"        <bond id=\"b34\" atomRefs2=\"a33 a34\" order=\"A\"/>\n" + 
				"        <bond id=\"b35\" atomRefs2=\"a26 a34\" order=\"1\"/>\n" + 
				"        <bond id=\"b36\" atomRefs2=\"a29 a34\" order=\"A\"/>\n" + 
				"        <bond id=\"b37\" atomRefs2=\"a31 a35\" order=\"1\"/>\n" + 
				"        <bond id=\"b38\" atomRefs2=\"a35 a36\" order=\"3\"/>\n" + 
				"        <bond id=\"b39\" atomRefs2=\"a26 a37\" order=\"1\"/>\n" + 
				"        <bond id=\"b40\" atomRefs2=\"a37 a38\" order=\"A\"/>\n" + 
				"        <bond id=\"b41\" atomRefs2=\"a38 a39\" order=\"A\"/>\n" + 
				"        <bond id=\"b42\" atomRefs2=\"a39 a40\" order=\"A\"/>\n" + 
				"        <bond id=\"b43\" atomRefs2=\"a40 a41\" order=\"1\"/>\n" + 
				"        <bond id=\"b44\" atomRefs2=\"a40 a42\" order=\"A\"/>\n" + 
				"        <bond id=\"b45\" atomRefs2=\"a42 a43\" order=\"A\"/>\n" + 
				"        <bond id=\"b46\" atomRefs2=\"a37 a43\" order=\"A\"/>\n" + 
				"        <bond id=\"b47\" atomRefs2=\"a44 a45\" order=\"1\"/>\n" + 
				"        <bond id=\"b48\" atomRefs2=\"a45 a46\" order=\"2\"/>\n" + 
				"        <bond id=\"b49\" atomRefs2=\"a45 a47\" order=\"1\"/>\n" + 
				"        <bond id=\"b50\" atomRefs2=\"a47 a48\" order=\"1\"/>\n" + 
				"        <bond id=\"b51\" atomRefs2=\"a48 a49\" order=\"A\"/>\n" + 
				"        <bond id=\"b52\" atomRefs2=\"a49 a50\" order=\"A\"/>\n" + 
				"        <bond id=\"b53\" atomRefs2=\"a50 a51\" order=\"A\"/>\n" + 
				"        <bond id=\"b54\" atomRefs2=\"a51 a52\" order=\"A\"/>\n" + 
				"        <bond id=\"b55\" atomRefs2=\"a52 a53\" order=\"A\"/>\n" + 
				"        <bond id=\"b56\" atomRefs2=\"a48 a53\" order=\"A\"/>\n" + 
				"        <bond id=\"b57\" atomRefs2=\"a1 a54\" order=\"1\"/>\n" + 
				"        <bond id=\"b58\" atomRefs2=\"a1 a55\" order=\"1\"/>\n" + 
				"        <bond id=\"b59\" atomRefs2=\"a1 a56\" order=\"1\"/>\n" + 
				"        <bond id=\"b60\" atomRefs2=\"a2 a57\" order=\"1\"/>\n" + 
				"        <bond id=\"b61\" atomRefs2=\"a3 a58\" order=\"1\"/>\n" + 
				"        <bond id=\"b62\" atomRefs2=\"a3 a59\" order=\"1\"/>\n" + 
				"        <bond id=\"b63\" atomRefs2=\"a3 a60\" order=\"1\"/>\n" + 
				"        <bond id=\"b64\" atomRefs2=\"a4 a61\" order=\"1\"/>\n" + 
				"        <bond id=\"b65\" atomRefs2=\"a5 a62\" order=\"1\"/>\n" + 
				"        <bond id=\"b66\" atomRefs2=\"a5 a63\" order=\"1\"/>\n" + 
				"        <bond id=\"b67\" atomRefs2=\"a6 a64\" order=\"1\"/>\n" + 
				"        <bond id=\"b68\" atomRefs2=\"a7 a65\" order=\"1\"/>\n" + 
				"        <bond id=\"b69\" atomRefs2=\"a8 a66\" order=\"1\"/>\n" + 
				"        <bond id=\"b70\" atomRefs2=\"a8 a67\" order=\"1\"/>\n" + 
				"        <bond id=\"b71\" atomRefs2=\"a12 a68\" order=\"1\"/>\n" + 
				"        <bond id=\"b72\" atomRefs2=\"a13 a69\" order=\"1\"/>\n" + 
				"        <bond id=\"b73\" atomRefs2=\"a14 a70\" order=\"1\"/>\n" + 
				"        <bond id=\"b74\" atomRefs2=\"a15 a71\" order=\"1\"/>\n" + 
				"        <bond id=\"b75\" atomRefs2=\"a17 a72\" order=\"1\"/>\n" + 
				"        <bond id=\"b76\" atomRefs2=\"a18 a73\" order=\"1\"/>\n" + 
				"        <bond id=\"b77\" atomRefs2=\"a19 a74\" order=\"1\"/>\n" + 
				"        <bond id=\"b78\" atomRefs2=\"a20 a75\" order=\"1\"/>\n" + 
				"        <bond id=\"b79\" atomRefs2=\"a20 a76\" order=\"1\"/>\n" + 
				"        <bond id=\"b80\" atomRefs2=\"a20 a77\" order=\"1\"/>\n" + 
				"        <bond id=\"b81\" atomRefs2=\"a22 a78\" order=\"1\"/>\n" + 
				"        <bond id=\"b82\" atomRefs2=\"a22 a79\" order=\"1\"/>\n" + 
				"        <bond id=\"b83\" atomRefs2=\"a22 a80\" order=\"1\"/>\n" + 
				"        <bond id=\"b84\" atomRefs2=\"a23 a81\" order=\"1\"/>\n" + 
				"        <bond id=\"b85\" atomRefs2=\"a23 a82\" order=\"1\"/>\n" + 
				"        <bond id=\"b86\" atomRefs2=\"a24 a83\" order=\"1\"/>\n" + 
				"        <bond id=\"b87\" atomRefs2=\"a24 a84\" order=\"1\"/>\n" + 
				"        <bond id=\"b88\" atomRefs2=\"a25 a85\" order=\"1\"/>\n" + 
				"        <bond id=\"b89\" atomRefs2=\"a25 a86\" order=\"1\"/>\n" + 
				"        <bond id=\"b90\" atomRefs2=\"a28 a87\" order=\"1\"/>\n" + 
				"        <bond id=\"b91\" atomRefs2=\"a28 a88\" order=\"1\"/>\n" + 
				"        <bond id=\"b92\" atomRefs2=\"a30 a89\" order=\"1\"/>\n" + 
				"        <bond id=\"b93\" atomRefs2=\"a32 a90\" order=\"1\"/>\n" + 
				"        <bond id=\"b94\" atomRefs2=\"a33 a91\" order=\"1\"/>\n" + 
				"        <bond id=\"b95\" atomRefs2=\"a38 a92\" order=\"1\"/>\n" + 
				"        <bond id=\"b96\" atomRefs2=\"a39 a93\" order=\"1\"/>\n" + 
				"        <bond id=\"b97\" atomRefs2=\"a42 a94\" order=\"1\"/>\n" + 
				"        <bond id=\"b98\" atomRefs2=\"a43 a95\" order=\"1\"/>\n" + 
				"        <bond id=\"b99\" atomRefs2=\"a44 a96\" order=\"1\"/>\n" + 
				"        <bond id=\"b100\" atomRefs2=\"a44 a97\" order=\"1\"/>\n" + 
				"        <bond id=\"b101\" atomRefs2=\"a44 a98\" order=\"1\"/>\n" + 
				"        <bond id=\"b102\" atomRefs2=\"a47 a99\" order=\"1\"/>\n" + 
				"        <bond id=\"b103\" atomRefs2=\"a49 a100\" order=\"1\"/>\n" + 
				"        <bond id=\"b104\" atomRefs2=\"a50 a101\" order=\"1\"/>\n" + 
				"        <bond id=\"b105\" atomRefs2=\"a51 a102\" order=\"1\"/>\n" + 
				"        <bond id=\"b106\" atomRefs2=\"a52 a103\" order=\"1\"/>\n" + 
				"        <bond id=\"b107\" atomRefs2=\"a53 a104\" order=\"1\"/>\n" + 
				"      </bondArray>\n" + 
				"    </molecule>\n" + 
				"  </MChemicalStruct>\n" + 
				"</MDocument>\n" + 
				"</cml>";
		
		String queryMolStr = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" + 
				"<cml xmlns=\"http://www.chemaxon.com\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.chemaxon.com/marvin/help/formats/schema/mrvSchema_14_7_7.xsd\" version=\"ChemAxon file format v14.7.7, generated by v14.7.7.0\">\n" + 
				"<MDocument>\n" + 
				"  <MChemicalStruct>\n" + 
				"    <molecule title=\"propranolol\" molID=\"m1\">\n" + 
				"      <atomArray atomID=\"a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16 a17 a18 a19 a20 a21 a22 a23 a24 a25 a26 a27 a28 a29 a30 a31 a32 a33 a34 a35 a36 a37 a38 a39 a40 a41 a42 a43 a44 a45 a46 a47 a48 a49 a50 a51 a52 a53 a54 a55 a56 a57 a58 a59 a60 a61 a62 a63 a64 a65 a66 a67 a68 a69 a70 a71 a72 a73 a74 a75 a76 a77 a78 a79 a80 a81 a82 a83 a84 a85 a86 a87 a88 a89 a90 a91 a92 a93 a94 a95 a96 a97 a98 a99 a100 a101 a102 a103 a104\" elementType=\"C C C N C C O C O C C C C C C C C C C C N C C C C C O C C C C C C C C N C C C C F C C C C O N C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C\" mrvMap=\"0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\" mrvPseudo=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H PSEUDO_H\" x2=\"-5.3347164873121224 -4.001037365484087 -4.001037365484087 -2.667358243656051 -1.3336791218280153 2.042810365310288E-14 1.9539925233402755E-14 1.3336791218280553 2.6673582436560905 4.001037365484127 5.334716487312165 5.334716487312169 6.668395609140206 8.00207473096824 8.002074730968236 6.6683956091402 6.6683956091402 5.334716487312164 4.0010373654841285 1.9481893063997529 3.2818684282277886 3.2818684282277886 4.615547550055823 5.949226671883859 7.282905793711895 8.616584915539931 10.081211950634465 10.081211950634469 8.616584915539931 7.990210485203195 6.458646766336054 5.553457477805647 6.179831908142382 7.711395627009522 5.832272335999319 5.205897905662584 9.242959345876663 8.337770057346251 8.964144487682983 10.495708206550123 11.122082636886855 11.400897495080535 10.774523064743804 -4.072707511243798 -4.072707511243796 -5.406386633071831 -2.7390283894157594 -2.739028389415757 -1.4053492675877215 -1.4053492675877206 -2.7390283894157554 -4.072707511243792 -4.072707511243795 -4.564716487312123 -6.668395609140158 -6.104716487312122 -5.334716487312122 -5.541037365484087 -4.001037365484087 -2.4610373654840867 -2.66735824365605 -1.6010973154350896 -0.6106929151377436 -1.3336791218280153 1.3336791218280548 0.6106929151377829 2.0566653285183274 4.001037365484136 6.668395609140211 9.335753852796277 9.33575385279627 8.002074730968236 5.334716487312164 2.6673582436560936 2.115572529513489 0.43420125562339856 0.8655143701862397 1.5590223270092929 2.646866105783297 4.736915027279273 3.5063632025159457 5.14581344383841 4.801802205674541 7.253459244093632 6.380623712415696 8.263337684753482 11.705050358652516 10.65685629095159 8.643809284628603 4.139556859210734 4.812224206355523 7.48352523710483 8.715741072958645 12.956348662226803 12.376528517092687 -2.532707511243798 -4.0727075112438 -5.612707511243798 -1.4053492675877246 -0.07167014575968622 -0.07167014575968467 -2.7390283894157523 -5.4063866330718255 -5.406386633071833\" y2=\"-7.700000000000015 -8.470000000000015 -10.010000000000016 -7.700000000000014 -8.470000000000015 -7.700000000000015 -6.160000000000015 -8.470000000000015 -7.700000000000015 -8.470000000000017 -7.7000000000000135 -6.16000000000001 -5.390000000000013 -6.160000000000016 -7.700000000000017 -8.470000000000015 -10.010000000000016 -10.780000000000015 -10.010000000000016 -13.21194674846017 -13.98194674846017 -15.521946748460168 -13.211946748460168 -13.981946748460167 -13.211946748460168 -13.981946748460167 -14.457832919797587 -15.997832919797586 -16.473719091135006 -17.880579095904615 -18.0415529293368 -16.795666757999378 -15.388806753229773 -15.227832919797585 -19.4484129341064 -20.855272938876006 -12.575086743690562 -11.32920057235314 -9.922340567583534 -9.761366734151348 -8.354506729381743 -11.007252905488766 -12.414112910258371 -15.977499389648438 -17.51749938964844 -18.28749938964844 -18.28749938964844 -19.827499389648438 -20.597499389648437 -22.137499389648436 -22.907499389648436 -22.13749938964844 -20.59749938964844 -6.36632087817198 -6.930000000000016 -9.033679121828051 -9.240000000000014 -10.010000000000016 -11.550000000000015 -10.010000000000016 -6.160000000000014 -9.986603939638815 -9.829739293002762 -6.930000000000016 -5.390000000000015 -9.829739293002762 -9.829739293002763 -5.390000000000006 -3.850000000000013 -5.39000000000002 -8.47000000000002 -10.780000000000017 -12.320000000000014 -10.780000000000017 -11.616150373422718 -12.518144884298673 -14.438578996503454 -15.546632898559668 -17.24671942088935 -16.387872749162906 -11.698243022625789 -11.759235718998182 -15.26683043868321 -14.454572420660273 -11.756443893962658 -12.28006224834698 -16.34167337154064 -17.538290165543312 -19.364142949175122 -17.963235701366855 -14.244988785128609 -9.811529535042848 -8.27160228455194 -10.559449431965731 -12.826482882147864 -15.977499389648436 -14.437499389648437 -15.97749938964844 -17.517499389648435 -19.827499389648438 -22.907499389648436 -24.447499389648435 -22.907499389648443 -19.827499389648445\"/>\n" + 
				"      <bondArray>\n" + 
				"        <bond id=\"b1\" atomRefs2=\"a1 a2\" order=\"1\"/>\n" + 
				"        <bond id=\"b2\" atomRefs2=\"a2 a3\" order=\"1\"/>\n" + 
				"        <bond id=\"b3\" atomRefs2=\"a2 a4\" order=\"1\"/>\n" + 
				"        <bond id=\"b4\" atomRefs2=\"a4 a5\" order=\"1\"/>\n" + 
				"        <bond id=\"b5\" atomRefs2=\"a5 a6\" order=\"1\"/>\n" + 
				"        <bond id=\"b6\" atomRefs2=\"a6 a7\" order=\"1\"/>\n" + 
				"        <bond id=\"b7\" atomRefs2=\"a6 a8\" order=\"1\"/>\n" + 
				"        <bond id=\"b8\" atomRefs2=\"a8 a9\" order=\"1\"/>\n" + 
				"        <bond id=\"b9\" atomRefs2=\"a9 a10\" order=\"1\"/>\n" + 
				"        <bond id=\"b10\" atomRefs2=\"a10 a11\" order=\"A\"/>\n" + 
				"        <bond id=\"b11\" atomRefs2=\"a11 a12\" order=\"A\"/>\n" + 
				"        <bond id=\"b12\" atomRefs2=\"a12 a13\" order=\"A\"/>\n" + 
				"        <bond id=\"b13\" atomRefs2=\"a13 a14\" order=\"A\"/>\n" + 
				"        <bond id=\"b14\" atomRefs2=\"a14 a15\" order=\"A\"/>\n" + 
				"        <bond id=\"b15\" atomRefs2=\"a15 a16\" order=\"A\"/>\n" + 
				"        <bond id=\"b16\" atomRefs2=\"a11 a16\" order=\"A\"/>\n" + 
				"        <bond id=\"b17\" atomRefs2=\"a16 a17\" order=\"A\"/>\n" + 
				"        <bond id=\"b18\" atomRefs2=\"a17 a18\" order=\"A\"/>\n" + 
				"        <bond id=\"b19\" atomRefs2=\"a18 a19\" order=\"A\"/>\n" + 
				"        <bond id=\"b20\" atomRefs2=\"a10 a19\" order=\"A\"/>\n" + 
				"        <bond id=\"b21\" atomRefs2=\"a20 a21\" order=\"1\"/>\n" + 
				"        <bond id=\"b22\" atomRefs2=\"a21 a22\" order=\"1\"/>\n" + 
				"        <bond id=\"b23\" atomRefs2=\"a21 a23\" order=\"1\"/>\n" + 
				"        <bond id=\"b24\" atomRefs2=\"a23 a24\" order=\"1\"/>\n" + 
				"        <bond id=\"b25\" atomRefs2=\"a24 a25\" order=\"1\"/>\n" + 
				"        <bond id=\"b26\" atomRefs2=\"a25 a26\" order=\"1\"/>\n" + 
				"        <bond id=\"b27\" atomRefs2=\"a26 a27\" order=\"1\"/>\n" + 
				"        <bond id=\"b28\" atomRefs2=\"a27 a28\" order=\"1\"/>\n" + 
				"        <bond id=\"b29\" atomRefs2=\"a28 a29\" order=\"1\"/>\n" + 
				"        <bond id=\"b30\" atomRefs2=\"a29 a30\" order=\"A\"/>\n" + 
				"        <bond id=\"b31\" atomRefs2=\"a30 a31\" order=\"A\"/>\n" + 
				"        <bond id=\"b32\" atomRefs2=\"a31 a32\" order=\"A\"/>\n" + 
				"        <bond id=\"b33\" atomRefs2=\"a32 a33\" order=\"A\"/>\n" + 
				"        <bond id=\"b34\" atomRefs2=\"a33 a34\" order=\"A\"/>\n" + 
				"        <bond id=\"b35\" atomRefs2=\"a26 a34\" order=\"1\"/>\n" + 
				"        <bond id=\"b36\" atomRefs2=\"a29 a34\" order=\"A\"/>\n" + 
				"        <bond id=\"b37\" atomRefs2=\"a31 a35\" order=\"1\"/>\n" + 
				"        <bond id=\"b38\" atomRefs2=\"a35 a36\" order=\"3\"/>\n" + 
				"        <bond id=\"b39\" atomRefs2=\"a26 a37\" order=\"1\"/>\n" + 
				"        <bond id=\"b40\" atomRefs2=\"a37 a38\" order=\"A\"/>\n" + 
				"        <bond id=\"b41\" atomRefs2=\"a38 a39\" order=\"A\"/>\n" + 
				"        <bond id=\"b42\" atomRefs2=\"a39 a40\" order=\"A\"/>\n" + 
				"        <bond id=\"b43\" atomRefs2=\"a40 a41\" order=\"1\"/>\n" + 
				"        <bond id=\"b44\" atomRefs2=\"a40 a42\" order=\"A\"/>\n" + 
				"        <bond id=\"b45\" atomRefs2=\"a42 a43\" order=\"A\"/>\n" + 
				"        <bond id=\"b46\" atomRefs2=\"a37 a43\" order=\"A\"/>\n" + 
				"        <bond id=\"b47\" atomRefs2=\"a44 a45\" order=\"1\"/>\n" + 
				"        <bond id=\"b48\" atomRefs2=\"a45 a46\" order=\"2\"/>\n" + 
				"        <bond id=\"b49\" atomRefs2=\"a45 a47\" order=\"1\"/>\n" + 
				"        <bond id=\"b50\" atomRefs2=\"a47 a48\" order=\"1\"/>\n" + 
				"        <bond id=\"b51\" atomRefs2=\"a48 a49\" order=\"A\"/>\n" + 
				"        <bond id=\"b52\" atomRefs2=\"a49 a50\" order=\"A\"/>\n" + 
				"        <bond id=\"b53\" atomRefs2=\"a50 a51\" order=\"A\"/>\n" + 
				"        <bond id=\"b54\" atomRefs2=\"a51 a52\" order=\"A\"/>\n" + 
				"        <bond id=\"b55\" atomRefs2=\"a52 a53\" order=\"A\"/>\n" + 
				"        <bond id=\"b56\" atomRefs2=\"a48 a53\" order=\"A\"/>\n" + 
				"        <bond id=\"b57\" atomRefs2=\"a1 a54\" order=\"1\"/>\n" + 
				"        <bond id=\"b58\" atomRefs2=\"a1 a55\" order=\"1\"/>\n" + 
				"        <bond id=\"b59\" atomRefs2=\"a1 a56\" order=\"1\"/>\n" + 
				"        <bond id=\"b60\" atomRefs2=\"a2 a57\" order=\"1\"/>\n" + 
				"        <bond id=\"b61\" atomRefs2=\"a3 a58\" order=\"1\"/>\n" + 
				"        <bond id=\"b62\" atomRefs2=\"a3 a59\" order=\"1\"/>\n" + 
				"        <bond id=\"b63\" atomRefs2=\"a3 a60\" order=\"1\"/>\n" + 
				"        <bond id=\"b64\" atomRefs2=\"a4 a61\" order=\"1\"/>\n" + 
				"        <bond id=\"b65\" atomRefs2=\"a5 a62\" order=\"1\"/>\n" + 
				"        <bond id=\"b66\" atomRefs2=\"a5 a63\" order=\"1\"/>\n" + 
				"        <bond id=\"b67\" atomRefs2=\"a6 a64\" order=\"1\"/>\n" + 
				"        <bond id=\"b68\" atomRefs2=\"a7 a65\" order=\"1\"/>\n" + 
				"        <bond id=\"b69\" atomRefs2=\"a8 a66\" order=\"1\"/>\n" + 
				"        <bond id=\"b70\" atomRefs2=\"a8 a67\" order=\"1\"/>\n" + 
				"        <bond id=\"b71\" atomRefs2=\"a12 a68\" order=\"1\"/>\n" + 
				"        <bond id=\"b72\" atomRefs2=\"a13 a69\" order=\"1\"/>\n" + 
				"        <bond id=\"b73\" atomRefs2=\"a14 a70\" order=\"1\"/>\n" + 
				"        <bond id=\"b74\" atomRefs2=\"a15 a71\" order=\"1\"/>\n" + 
				"        <bond id=\"b75\" atomRefs2=\"a17 a72\" order=\"1\"/>\n" + 
				"        <bond id=\"b76\" atomRefs2=\"a18 a73\" order=\"1\"/>\n" + 
				"        <bond id=\"b77\" atomRefs2=\"a19 a74\" order=\"1\"/>\n" + 
				"        <bond id=\"b78\" atomRefs2=\"a20 a75\" order=\"1\"/>\n" + 
				"        <bond id=\"b79\" atomRefs2=\"a20 a76\" order=\"1\"/>\n" + 
				"        <bond id=\"b80\" atomRefs2=\"a20 a77\" order=\"1\"/>\n" + 
				"        <bond id=\"b81\" atomRefs2=\"a22 a78\" order=\"1\"/>\n" + 
				"        <bond id=\"b82\" atomRefs2=\"a22 a79\" order=\"1\"/>\n" + 
				"        <bond id=\"b83\" atomRefs2=\"a22 a80\" order=\"1\"/>\n" + 
				"        <bond id=\"b84\" atomRefs2=\"a23 a81\" order=\"1\"/>\n" + 
				"        <bond id=\"b85\" atomRefs2=\"a23 a82\" order=\"1\"/>\n" + 
				"        <bond id=\"b86\" atomRefs2=\"a24 a83\" order=\"1\"/>\n" + 
				"        <bond id=\"b87\" atomRefs2=\"a24 a84\" order=\"1\"/>\n" + 
				"        <bond id=\"b88\" atomRefs2=\"a25 a85\" order=\"1\"/>\n" + 
				"        <bond id=\"b89\" atomRefs2=\"a25 a86\" order=\"1\"/>\n" + 
				"        <bond id=\"b90\" atomRefs2=\"a28 a87\" order=\"1\"/>\n" + 
				"        <bond id=\"b91\" atomRefs2=\"a28 a88\" order=\"1\"/>\n" + 
				"        <bond id=\"b92\" atomRefs2=\"a30 a89\" order=\"1\"/>\n" + 
				"        <bond id=\"b93\" atomRefs2=\"a32 a90\" order=\"1\"/>\n" + 
				"        <bond id=\"b94\" atomRefs2=\"a33 a91\" order=\"1\"/>\n" + 
				"        <bond id=\"b95\" atomRefs2=\"a38 a92\" order=\"1\"/>\n" + 
				"        <bond id=\"b96\" atomRefs2=\"a39 a93\" order=\"1\"/>\n" + 
				"        <bond id=\"b97\" atomRefs2=\"a42 a94\" order=\"1\"/>\n" + 
				"        <bond id=\"b98\" atomRefs2=\"a43 a95\" order=\"1\"/>\n" + 
				"        <bond id=\"b99\" atomRefs2=\"a44 a96\" order=\"1\"/>\n" + 
				"        <bond id=\"b100\" atomRefs2=\"a44 a97\" order=\"1\"/>\n" + 
				"        <bond id=\"b101\" atomRefs2=\"a44 a98\" order=\"1\"/>\n" + 
				"        <bond id=\"b102\" atomRefs2=\"a47 a99\" order=\"1\"/>\n" + 
				"        <bond id=\"b103\" atomRefs2=\"a49 a100\" order=\"1\"/>\n" + 
				"        <bond id=\"b104\" atomRefs2=\"a50 a101\" order=\"1\"/>\n" + 
				"        <bond id=\"b105\" atomRefs2=\"a51 a102\" order=\"1\"/>\n" + 
				"        <bond id=\"b106\" atomRefs2=\"a52 a103\" order=\"1\"/>\n" + 
				"        <bond id=\"b107\" atomRefs2=\"a53 a104\" order=\"1\"/>\n" + 
				"      </bondArray>\n" + 
				"    </molecule>\n" + 
				"  </MChemicalStruct>\n" + 
				"</MDocument>\n" + 
				"</cml>";
		
		
			try {
				Molecule target = MolImporter.importMol(targetMolStr);
				Molecule query = MolImporter.importMol(queryMolStr);
				
				MolSearchOptions searchOpts = new MolSearchOptions(SearchConstants.FULL);
				searchOpts.setStereoSearchType(SearchConstants.STEREO_SPECIFIC);
				searchOpts.setDoubleBondStereoMatchingMode(StereoConstants.DBS_ALL);
				searchOpts.setExactBondMatching(true);
				searchOpts.setStereoModel(SearchConstants.STEREO_MODEL_LOCAL);
				searchOpts.setOrderSensitiveSearch(true); 
				searchOpts.setIgnoreCumuleneOrRingCisTransStereo(true); 
				searchOpts.setIgnoreAxialStereo(false);
				searchOpts.setIgnoreSynAntiStereo(true);
				MolSearch search = new MolSearch();
				search.setSearchOptions(searchOpts);
				search.setTarget(target);
				search.setQuery(query);
				while (true) {
					isomorphism = search.findNext();
					if (isomorphism == null) {
						break;
					}
				}
		
			}	catch (Exception e){
				e.printStackTrace();
			}

%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="Content-Script-Type" content="type"/>
<meta http-equiv="Content-Style-Type" content="text/css"/>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title>Out of memory test</title>
<link rel="stylesheet" href="../includes/epoch.css" type="text/css">
<script src="../js/jslib.js" type="text/javascript"></script>
</head>

<body style="overflow:auto;">

<br>

<P class="boldtext big" align=center>
Out of memory test
</P>
<P>
<table>
<tr>
<td align="left" class="regtext" >
Found this isomorphism: 
<%= Utils.join(isomorphism) %>
</td>
</tr>
<tr>
<td align="left" class="regtext" >
<br><br><a href="welcome.html">Back</a> to public ACE pages.
</td>
</tr>

</table>
</P>
</body>
</html>
